#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2016-12-13 15:50:04 +0000 (Tue, 13 Dec 2016)
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

version: '3'
services:
  zookeeper-dev:
    image: harisekhon/zookeeper-dev:${VERSION:-latest}
    ports:
      - 2181:2181
      - 3181:3181
      - 4181:4181
