#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2019-03-01 17:11:46 +0000 (Fri, 01 Mar 2019)
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

version: '3'
services:
  opentsdb:
    image: harisekhon/opentsdb:${VERSION:-latest}
  hbase:
    image: harisekhon/hbase:${HBASE_VERSION:-latest}
  zookeeper:
    image: harisekhon/zookeeper:${ZOOKEEPER_VERSION:-latest}
