#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2016-12-09 22:13:19 +0000 (Fri, 09 Dec 2016)
#
#  https://github.com/HariSekhon/Dockerfiles
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

version: '3'
services:
  hbase-master:
    image: harisekhon/hbase:${VERSION:-latest}
    command: master
    ports:
      - 16000:16000
      - 16010:16010
  hbase-regionserver:
    image: harisekhon/hbase:${VERSION:-latest}
    command: regionserver
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
  hbase-thrift:
    image: harisekhon/hbase:${VERSION:-latest}
    command: thrift
    ports:
      - 9090:9090
      - 9095:9095
  hbase-stargate:
    image: harisekhon/hbase:${VERSION:-latest}
    command: stargate
    ports:
      - 8080:8080
      - 8085:8085
  zookeeper:
    image: harisekhon/zookeeper:latest
    ports:
      - 2181:2181
