#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/harisekhon/Dockerfiles
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

name: Mac 10.15

#env:
#  DEBUG: 1

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * *'

jobs:
  build:
    #name: build
    timeout-minutes: 20
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-Dockerfiles  # -${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-Dockerfiles
    - uses: actions/cache@v1
      with:
        path: ~/.cpanm
        key: ${{ runner.os }}-cpanm-Dockerfiles-${{ hashFiles('**/cpan-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-cpanm-Dockerfiles
    - name: brew update
      run: which brew && brew update || echo
    - name: init
      run: make init
    - name: build
      run: make ci
    - name: test
      run: make test
